# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-01 17:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ckan_id', models.CharField(max_length=200)),
                ('insert_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='insert date')),
                ('metadata_modified', models.DateTimeField(verbose_name='metadata_modified')),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ckan_id', models.CharField(max_length=200)),
                ('insert_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='insert date')),
            ],
        ),
        migrations.CreateModel(
            name='LoadRound',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roundn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ODPMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(blank=True, max_length=200, null=True)),
                ('insert_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='insert date')),
                ('ckan_version', models.CharField(blank=True, max_length=200, null=True)),
                ('site_description', models.CharField(blank=True, max_length=2000, null=True)),
                ('locale_default', models.CharField(blank=True, max_length=10, null=True)),
                ('load_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_analytics.LoadRound')),
            ],
        ),
        migrations.CreateModel(
            name='OpenDataPortal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('insert_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='insert date')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('display_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ckan_id', models.CharField(max_length=200)),
                ('translation', models.CharField(max_length=200)),
                ('insert_date', models.DateTimeField(default=datetime.datetime.now, verbose_name='insert date')),
                ('datasets', models.ManyToManyField(blank=True, to='tag_analytics.Dataset')),
                ('load_round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_analytics.LoadRound')),
            ],
        ),
        migrations.AddField(
            model_name='loadround',
            name='open_data_portal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_analytics.OpenDataPortal'),
        ),
        migrations.AddField(
            model_name='group',
            name='load_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_analytics.LoadRound'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='groups',
            field=models.ManyToManyField(blank=True, to='tag_analytics.Group'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='load_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tag_analytics.LoadRound'),
        ),
    ]
