# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-02 13:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadround',
            name='insert_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='insert date'),
        ),
    ]
