# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0003_loadround_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='n_resources',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='n_tags',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='n_packages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='odpmetadata',
            name='n_packages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
