# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-13 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0004_auto_20160304_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='metadata_modified',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='metadata_modified'),
        ),
        migrations.AlterField(
            model_name='loadround',
            name='success',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='display_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='translation',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
