# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0005_auto_20160313_1152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coocurrence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(default=0)),
                ('tag_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_1_set', to='tag_analytics.Tag')),
                ('tag_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tag_2_set', to='tag_analytics.Tag')),
            ],
        ),
    ]
