# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-22 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0006_coocurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='coocurrence',
            name='similarity',
            field=models.FloatField(default=0),
        ),
    ]
