# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-29 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0007_coocurrence_similarity'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='translation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
