# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-30 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0008_group_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='main_tag',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='similar_tags',
            field=models.ManyToManyField(blank=True, related_name='_tag_similar_tags_+', to='tag_analytics.Tag'),
        ),
    ]
