# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0010_tagmeaning_tagtranslation'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('groups', models.ManyToManyField(blank=True, to='tag_analytics.Group')),
            ],
        ),
    ]
