# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0012_globaltag'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltag',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
