# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0013_globaltag_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltag',
            name='broader',
            field=models.ManyToManyField(blank=True, related_name='_globaltag_broader_+', to='tag_analytics.GlobalTag'),
        ),
        migrations.AddField(
            model_name='globaltag',
            name='narrower',
            field=models.ManyToManyField(blank=True, related_name='_globaltag_narrower_+', to='tag_analytics.GlobalTag'),
        ),
        migrations.AddField(
            model_name='globaltag',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_globaltag_related_+', to='tag_analytics.GlobalTag'),
        ),
        migrations.AddField(
            model_name='globaltag',
            name='uri',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
