# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-14 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0014_auto_20160413_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalgroup',
            name='uri',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
