# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-18 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0015_globalgroup_uri'),
    ]

    operations = [
        migrations.AddField(
            model_name='globaltag',
            name='global_groups',
            field=models.ManyToManyField(blank=True, to='tag_analytics.GlobalGroup'),
        ),
    ]
