# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-19 16:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag_analytics', '0016_globaltag_global_groups'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globaltag',
            old_name='global_groups',
            new_name='globalgroups',
        ),
    ]
